<?php
// module/Registration/view/registration/registration/registration.phtml:

$title = 'Register | Product';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">
                <h3>Registration Product</h3>
            </header>

            <div class="panel-body">
                <div class="content">
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>

                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Product Category</label>
                                <?php echo $this->formRow($form->get('productCatId')); ?>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Product Name</label>
                                <?php echo $this->formRow($form->get('productName')); ?>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Description</label>
                                <?php echo $this->formRow($form->get('description')); ?>
                            </div>
                        </div>


                        <div class="col-md-5">
                            <label>MRP</label>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('mrp')); ?>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Price</label>
                                <?php echo $this->formRow($form->get('price')); ?>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Base Value</label>
                                <?php echo $this->formRow($form->get('baseValue')); ?>
                            </div>
                        </div>

                    </div>


                    <div class="text-center">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </div>
                    <div class="clearfix"></div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </section>
        <!--end-->
    </div>
</div>
<!--Charts Plugin--> 
<script src="/js/chartist.min.js"></script>

<!--<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>-->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $('#bday').datepicker({
            format: "yyyy-mm-dd",
//    maxDate : 'now',
            startView: 1,
            minViewMode: 1,
            maxViewMode: 3,
            autoclose: true,
        })
                .datepicker('update', new Date());
<?php if ($msg != "") { ?>
            alert("Registerd Successfully");
<?php } ?>
    });
</script>