<section id="about-us">
     <?php $localTitle = 'Grow Dream Maker Marketing Pvt.Ltd';?>
            <div class="container">			
                <div class="skill-wrap clearfix">			
                    <div class="center wow fadeInDown">
                        <h2>About <span><?php echo $localTitle; ?>.</span></h2>
                        <p class="lead"><?php echo $localTitle; ?>is formulated under the guidance of its promoters having a vast and sound experience in 
                            product design, manufacturing, quality systems, marketing and sales industry. The company was formulated for manufacturing, direct sales and distribution of its quality products 
                            considering the Direct Selling Guidelines 2016 issued by government of India in regards to the conduct of direct selling business in a 
                            healthy, ethical and consumer friendly way.</p>
                    </div>

                    <div class="row">
                        <div class="wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                            <div class="col-sm-4">
                                <img src="/images/vision.jpg" alt="Vision" class="img img-thumbnail">
                            </div>
                            <div class="col-sm-7"> <p class="lead" style="text-align: justify;"><b>VISION :</b> To become No 1 Direct Marketing Organization in the country by promoting "Direct Selling" of quality products and services 
                                    by creating vibrant Self Help Teams with a view to alleviate poverty and eliminate negativity by generation of self-employment through 
                                    motivation by using state-of-the-art technology and for creating vibrant Self Help Teams across the country.</p></div>
                        </div>				
                    </div>

                    <div class="row" style="margin-top: 30px;">
                        <div class="wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">                            
                            <div class="col-sm-7"> <p class="lead" style="text-align: justify;"><b>MISSION :</b> To strive hard continuously and constantly to make every individual customer financially self-reliant, 
                                    economically and socially strong through the Self-Help Team Concept.</p>
                            </div>
                            <div class="col-sm-4">
                                <img src="/images/mission.jpg" alt="Mission" class="img img-thumbnail">
                            </div>
                        </div>				
                    </div>	
                </div>
                <!--
                                 our-team 
                                <div class="team">
                                    <div class="center wow fadeInDown">
                                        <h2>Team of <span>Gp.</span></h2>
                                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
                                    </div>
                
                                    <div class="row clearfix">
                                        <div class="col-md-4 col-sm-6">	
                                            <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                                <div class="media">
                                                    <div class="pull-left">
                                                        <a href="#"><img class="media-object" src="images/man1.jpg" alt=""></a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4>Jhon Doe</h4>
                                                        <h5>Founder and CEO</h5>
                                                        <ul class="tag clearfix">
                                                            <li class="btn"><a href="#">Web</a></li>
                                                            <li class="btn"><a href="#">Ui</a></li>
                                                            <li class="btn"><a href="#">Ux</a></li>
                                                            <li class="btn"><a href="#">Photoshop</a></li>
                                                        </ul>
                
                                                        <ul class="social_icons">
                                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>/.media 
                                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                                            </div>
                                        </div>/.col-lg-4 
                
                
                                        <div class="col-md-4 col-sm-6 col-md-offset-2">	
                                            <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                                <div class="media">
                                                    <div class="pull-left">
                                                        <a href="#"><img class="media-object" src="images/man2.jpg" alt=""></a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4>Jhon Doe</h4>
                                                        <h5>Founder and CEO</h5>
                                                        <ul class="tag clearfix">
                                                            <li class="btn"><a href="#">Web</a></li>
                                                            <li class="btn"><a href="#">Ui</a></li>
                                                            <li class="btn"><a href="#">Ux</a></li>
                                                            <li class="btn"><a href="#">Photoshop</a></li>
                                                        </ul>
                                                        <ul class="social_icons">
                                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>/.media 
                                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                                            </div>
                                        </div>/.col-lg-4 					
                                    </div> /.row 
                                    <div class="row team-bar">
                                        <div class="first-one-arrow hidden-xs">
                                            <hr>
                                        </div>
                                        <div class="first-arrow hidden-xs">
                                            <hr> <i class="fa fa-angle-up"></i>
                                        </div>
                                        <div class="second-arrow hidden-xs">
                                            <hr> <i class="fa fa-angle-down"></i>
                                        </div>
                                        <div class="third-arrow hidden-xs">
                                            <hr> <i class="fa fa-angle-up"></i>
                                        </div>
                                        <div class="fourth-arrow hidden-xs">
                                            <hr> <i class="fa fa-angle-down"></i>
                                        </div>
                                    </div> skill_border       
                
                                    <div class="row clearfix">   
                                        <div class="col-md-4 col-sm-6 col-md-offset-2">	
                                            <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                                                <div class="media">
                                                    <div class="pull-left">
                                                        <a href="#"><img class="media-object" src="images/man3.jpg" alt=""></a>
                                                    </div>
                
                                                    <div class="media-body">
                                                        <h4>Jhon Doe</h4>
                                                        <h5>Founder and CEO</h5>
                                                        <ul class="tag clearfix">
                                                            <li class="btn"><a href="#">Web</a></li>
                                                            <li class="btn"><a href="#">Ui</a></li>
                                                            <li class="btn"><a href="#">Ux</a></li>
                                                            <li class="btn"><a href="#">Photoshop</a></li>
                                                        </ul>
                                                        <ul class="social_icons">
                                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>/.media 
                                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                                            </div>
                                        </div>
                                        <div class="col-md-4 col-sm-6 col-md-offset-2">
                                            <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                                                <div class="media">
                                                    <div class="pull-left">
                                                        <a href="#"><img class="media-object" src="images/man4.jpg" alt=""></a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4>Jhon Doe</h4>
                                                        <h5>Founder and CEO</h5>
                                                        <ul class="tag clearfix">
                                                            <li class="btn"><a href="#">Web</a></li>
                                                            <li class="btn"><a href="#">Ui</a></li>
                                                            <li class="btn"><a href="#">Ux</a></li>
                                                            <li class="btn"><a href="#">Photoshop</a></li>
                                                        </ul>
                                                        <ul class="social_icons">
                                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>/.media 
                                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                                            </div>
                                        </div>
                                    </div>	/.row
                                </div>section-->
            </div><!--/.container-->
        </section><!--/about-us-->