 <div class="map">
            <!--<div id="google-map" data-latitude="40.713732" data-longitude="-74.0092704"></div>-->
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3772.942260252408!2d75.74105556467109!3d18.9781572371442!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc52aedb871008f%3A0x691f6e0d5b3e0772!2sPalwan+Chowk!5e0!3m2!1sen!2sin!4v1510134589353" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
       <div class="container">
            <h1>Contact Address</h1><br>
            <div class="row text-center">
                <div class="col-sm-3 col-xs-6 first-box">
                    <h1><span class="glyphicon glyphicon-earphone"></span></h1>
                    <h3>Phone</h3>
                    <p>+91 9561808020 <br> +91 9405345752</p><br>
                </div>
                <div class="col-sm-3 col-xs-6 second-box">
                    <h1><span class="glyphicon glyphicon-home"></span></h1>
                    <h3>Location</h3>
                    <p>SANT NAMDEV NAGAR DHANORA ROAD BEED BEED Bid MH 431122 IN</p><br>
                </div>
                <div class="col-sm-3 col-xs-6 third-box">
                    <h1><span class="glyphicon glyphicon-send"></span></h1>
                    <h3>E-mail</h3>
                    <p><br>info@growdreammaker.com </p><br>
                </div>
                <a style="color: #000;" target="_blank" href="http://growdreammaker.com/">
                    <div class="col-sm-3 col-xs-6 fourth-box">
                        <h1><span class="glyphicon glyphicon-leaf"></span></h1>
                        <h3>Web</h3>
                        <p><br>www.growdreammaker.com</p><br>
                    </div></a>
            </div>
        </div>
        <section id="contact-page">
            <div class="container">
                <div class="center" style="margin-bottom: -50px !important;">        
                    <h2 style="margin-top: 20px;">Drop Your Message</h2>
                    <p class="lead">We are Happy to hear you...</p>
                </div> 
                <div class="row contact-wrap" > 
                     <div class="col-sm-8 col-sm-offset-2">
                        <div id="sendmessage">Your message has been sent. Thank you!</div>
                        <div id="errormessage"></div>
                        <form action="" method="post" role="form" class="contactForm" >
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                                <div class="validation"></div>
                            </div>

                            <div class="text-center"><button type="submit" class="btn btn-primary btn-lg">Send Message</button></div>
                        </form>     
                    </div>
                </div><!--/.row-->
            </div><!--/.container-->
        </section><!--/#contact-page-->