        <div class="slider">
            <div class="container-fluid">
                <div id="about-slider">
                    <div id="carousel-slider" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators visible-xs">
                            <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-slider" data-slide-to="1"></li>
                            <li data-target="#carousel-slider" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="/images/slider2.jpg" class="img-responsive" alt=""> 
                            </div>
                            <div class="item">
                                <img src="/images/slider3.jpg" class="img-responsive" alt=""> 
                            </div> 
                            <div class="item">
                                <img src="/images/slider4.jpg" class="img-responsive" alt=""> 
                            </div> 
                        </div>

                        <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
                            <i class="fa fa-angle-left"></i> 
                        </a>

                        <a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
                            <i class="fa fa-angle-right"></i> 
                        </a>
                    </div> <!--/#carousel-slider-->
                </div><!--/#about-slider-->
            </div>
        </div>

        <section id="feature" >
            <div class="container">
                <div class="center wow fadeInDown">
                    <h2>Company Profile</h2>
                    <p class="lead"><?php //echo $localTitle; ?>is formulated under the guidance of its promoters having a vast and sound experience 
                        in product design, manufacturing, quality systems, marketing and sales industry.</p>
                    <p class="lead"><?php  ?>The company was formulated for manufacturing, direct sales and distribution of its quality products 
                        considering the Direct Selling Guidelines 2016 issued by government of India in regards to the conduct of direct selling business 
                        in a healthy, ethical and consumer friendly way.</p>
                </div>

<!--                <div class="row">
                    <div class="features">
                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-laptop"></i>
                                <h2>Fresh and Clean</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4

                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-comments"></i>
                                <h2>Retina ready</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4

                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-cloud-download"></i>
                                <h2>Easy to customize</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4

                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-leaf"></i>
                                <h2>Adipisicing elit</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4

                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-cogs"></i>
                                <h2>Sed do eiusmod</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4

                        <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="feature-wrap">
                                <i class="fa fa-heart"></i>
                                <h2>Labore et dolore</h2>
                                <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
                            </div>
                        </div>/.col-md-4
                    </div>/.services
                </div>/.row    -->
            </div><!--/.container-->
        </section>