<section id="about-us">
    <?php $localTitle = 'Grow Dream Maker Marketing Pvt.Ltd'; ?>
    <div class="container">		
        <!--our-team--> 
        <div class="row" style="margin-top: 35px;">
        <div class="team">
            <div class="center wow fadeInDown">
                <h2>Certification and Legal Documents <br><span> <?= $localTitle?></span></h2>
            </div>
            <div class="row clearfix">
                <div class="col-md-4 col-sm-6">	
                    <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <div class="media" style="overflow: auto; height: 300px;">
                            <div class="media-body">
                                <a href="/documents/INCORPORATION.jpg" target="blank"><img src="/documents/INCORPORATION.jpg"  alt="Incorporation" class="img img-responsive img-thumbnail"/></a>
                            </div>
                        </div> <!--/.media--> 
                        <p>Incorporation Certificate</p>
                    </div>
                </div><!--/.col-lg-4--> 


                <div class="col-md-4 col-sm-6 col-md-offset-2">	
                    <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <div class="media" style="overflow: auto; height: 300px;">
                            <div class="media-body">
                                <a href="/documents/PAN.pdf" target="blank"><img src="/documents/PAN.jpg" alt="Pan card" class="img img-responsive img-thumbnail"/></a>
                            </div>
                        </div> <!--/.media--> 
                        <p>Pan Card</p>
                        </div>
                </div> <!--/.col-lg-4--> 					
            </div> <!--/.row--> 
            <!-- Horizontal bar-->
            <div class="row team-bar">
                <div class="first-one-arrow hidden-xs">
                    <hr>
                </div>
                <div class="first-arrow hidden-xs">
                    <hr> <i class="fa fa-angle-up"></i>
                </div>
                <div class="second-arrow hidden-xs">
                    <hr> <i class="fa fa-angle-down"></i>
                </div>
                <div class="third-arrow hidden-xs">
                    <hr> <i class="fa fa-angle-up"></i>
                </div>
                <div class="fourth-arrow hidden-xs">
                    <hr> <i class="fa fa-angle-down"></i>
                </div>
            </div>  <!--skill_border-->       

            <div class="row clearfix">   
                <div class="col-md-4 col-sm-6 col-md-offset-2">	
                    <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="media" style="overflow: auto; height: 300px;">
                            <div class="media-body">
                                <a href="/documents/MOA_AOA.pdf" target="blank"><img src="/documents/MOA_AOA.JPG" alt="Pan card" class="img img-responsive img-thumbnail"/></a>
                            </div>
                        </div> <!--/.media--> 
                        <p>MEMORANDUM OF ASSOCIATION & ARTICLES OF ASSOCIATION</p>
                    </div>
                </div>
<!--                
                <div class="col-md-4 col-sm-6 col-md-offset-2">
                    <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                         <div class="media" style="overflow: auto; height: 300px;">
                            <div class="media-body">
                                <a href="/documents/PAN.pdf" target="blank"><img src="/documents/PAN.jpg" alt="Pan card" class="img img-responsive img-thumbnail"/></a>
                            </div>
                        </div> /.media 
                        <p></p>
                    </div>
                </div>
                -->
            </div> <!-- /.row-->
        </div> <!-- team -->
    </div><!-- /.row -->
    </div><!--/.container-->
</section><!--/about-us-->