<section id="portfolio">
            <div class="container">
                <div class="center">
                    <h2>Products</h2>
                    </div>


                <ul class="portfolio-filter text-center">
                    <li><a class="btn btn-default active" href="#" data-filter="*">All Products</a></li>
                    <li><a class="btn btn-default" href="#" data-filter=".bootstrap">Home Maker</a></li>
                    <li><a class="btn btn-default" href="#" data-filter=".html">Electronics</a></li>
                    <li><a class="btn btn-default" href="#" data-filter=".wordpress">Textiles</a></li>
                </ul><!--/#portfolio-filter-->

                <div class="row">
                    <div class="portfolio-items">
                        <div class="portfolio-item plan agree col-xs-12 col-sm-4 col-md-3" style="padding:40px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/product_desc.jpg" alt="" >
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Product Description</a></h3>
                                    <p>Detailed Product Description and with Uses</p>
                                    <a class="preview" href="/images/products/product_desc.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item plan col-xs-12 col-sm-4 col-md-3" style="padding:40px 30px 30px 30px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/products.jpg" alt="" >
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Product Description</a></h3>
                                    <p>Detailed Product Description and their BV's</p>
                                    <a class="preview" href="/images/products/products.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3" style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/001.jpg" alt="" >
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Bio</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/001.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3" style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/002.jpg" alt="">
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Bio</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/002.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3" style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/003.jpg" alt="">
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Soil</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/003.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3" style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/004.jpg" alt="">
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Bio</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/004.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3"  style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/005.jpg" alt="">
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Bio</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/005.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    <div class="portfolio-item agree col-xs-12 col-sm-4 col-md-3" style="padding:40px 90px 80px 80px;">
                        <div class="recent-work-wrap">
                            <img class="img img-responsive" src="/images/products/006.jpg" alt="">
                            <div class="overlay">
                                <div class="recent-work-inner">
                                    <h3><a href="#">Grow Dream Bio</a></h3>
                                    <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority</p>-->
                                    <a class="preview" href="/images/products/006.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                                </div> 
                            </div>
                        </div>
                    </div><!--<!--/.portfolio-item-->
                    </div>
                </div>
            </div>
        </section><!--/#portfolio-item-->