<?php
$title = 'base value';
$this->headTitle($title);

$bverrors=$form->getMessages();
?>
<div class="container">
    <div class="row">
         <button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#myModal">Add</button>
        <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Profile</h4>
        </div>
        <div class="modal-body">
          <div class="row1">
                <?php
                $form = $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>bvrate</label>
                            <?php echo $this->formRow($form->get('bvrate')); ?>
                            <!--<input type="hidden" name="id" id="id" />-->
                        </div>
                    </div>
                </div>
              <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>appliedFrom</label>
                            <?php echo $this->formRow($form->get('appliedFrom')); ?>
                        </div>
                    </div>
              </div>
               
                <div class="row">
                <div class="text-center col-md-6">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
                    
                <div class="clearfix"></div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
        
      </div>
      
    </div>
  </div>
    </div>
    
    
    <div class="table-responsive">
                        <table class="table table-hover" id="userList">
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>id</th>
                                    <th>Bv Rate</th>
                                    <th>Applied From</th>
                                    <th>created</th>
                                </tr>
                            </thead>
                        </table>
                    
    </div>
</div>
<link href="/datatable/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
<link href="/datatable/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
 
<script src="/datatable/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="/datatable/dataTables.bootstrap.min.js" type="text/javascript"></script>
 
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $('#appliedFrom').datepicker({
            format: "yyyy-mm-dd",
            minDate:  new Date(), // Current day
//            startView: 0,
//            minViewMode: 0,
//            maxViewMode: 3,
            autoclose: true,
        })
                .datepicker('update', new Date());
    });

td = $('#userList').DataTable({
                                // stateSave: true,
                                responsive: true,
                                "language": {
                                    "processing": '<div class="LoadingMsg"><img src="/images/loading.gif">&nbsp; Loading....</div>',
//                                    "info": "of _TOTAL_ entries.",
//                                    "lengthMenu": "Showing _MENU_",
                                },
                                "processing": true,
                                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                                "pageLength": 10,
                                "serverSide": true,
                                "ajax": {
                                    "url": "/dashboard/dashboard/basevalueserverside",
//                                    "data": function (post) {
//                                        post.org = orgnization;
//                                        post.category = category;
//                                        post.dept = dept;
//                                        post.branch = branch;
//
//                                    },
                                },
                                "fnRowCallback": function (nRow, aData, iDisplayIndex) {
//                                        console.log(aData);
                                    var $nRow = $(nRow); // cache the row wrapped up in jQuery
                                    //$("#userList_length").css('float', 'left');
                                    //$("#userList_info").css('float', 'left');
                                    //$("#userList_info").css('margin', '0 0 0 5px');
                                },
                                        "columnDefs": [
                                        {
                                            "targets": [0],
                                            "orderable": false,
                                            "searchable": false,
                                        },
                                        {
                                            "targets": [1],
                                            "visible": false,
                                            "searchable": false,
                                        },
                                    ],

        //                                "sDom": '<"top">rt<"bottom listingTableFooter"<"listingPageCountDiv"li><"clear"><"listingPaginationDiv"p>><"clear">',
                                "order": [[1, 'desc']],
                            });
                    
   <?php if(!empty($bverrors)){ ?>
           $("#myModal").modal("show");
   <?php  } ?>
</script>