<style type="text/css">
    /*Now the CSS*/

    * {margin: 0; padding: 0;}
    .tree ul {
        padding-top: 20px; position: relative;
        transition: all 0.5s;
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
    }

    .tree li {
        float: left; text-align: center;
        list-style-type: none;
        position: relative;
        padding: 20px 5px 0 5px;

        transition: all 0.5s;
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
    }

    /*We will use ::before and ::after to draw the connectors*/

    .tree li::before, .tree li::after{
        content: '';
        position: absolute; top: 0; right: 50%;
        border-top: 1px solid #ccc;
        width: 50%; height: 20px;
    }
    .tree li::after{
        right: auto; left: 50%;
        border-left: 1px solid #ccc;
    }

    /*We need to remove left-right connectors from elements without 
    any siblings*/
    .tree li:only-child::after, .tree li:only-child::before {
        display: none;
    }

    /*Remove space from the top of single children*/
    .tree li:only-child{ padding-top: 0;}

    /*Remove left connector from first child and 
    right connector from last child*/
    .tree li:first-child::before, .tree li:last-child::after{
        border: 0 none;
    }
    /*Adding back the vertical connector to the last nodes*/
    .tree li:last-child::before{
        border-right: 1px solid #ccc;
        border-radius: 0 5px 0 0;
        -webkit-border-radius: 0 5px 0 0;
        -moz-border-radius: 0 5px 0 0;
    }
    .tree li:first-child::after{
        border-radius: 5px 0 0 0;
        -webkit-border-radius: 5px 0 0 0;
        -moz-border-radius: 5px 0 0 0;
    }

    /*Time to add downward connectors from parents*/
    .tree ul ul::before{
        content: '';
        position: absolute; top: 0; left: 50%;
        border-left: 1px solid #ccc;
        width: 0; height: 20px;
    }

    .tree li a{
        border: 1px solid #ccc;
        padding: 5px 10px;
        text-decoration: none;
        color: #666;
        font-family: arial, verdana, tahoma;
        font-size: 11px;
        display: inline-block;

        border-radius: 5px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;

        transition: all 0.5s;
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
    }

    /*Time for some hover effects*/
    /*We will apply the hover effect the the lineage of the element also*/
    .tree li a:hover, .tree li a:hover+ul li a {
        background: #c8e4f8; color: #000; border: 1px solid #94a0b4;
    }
    /*Connector styles on hover*/
    .tree li a:hover+ul li::after, 
    .tree li a:hover+ul li::before, 
    .tree li a:hover+ul::before, 
    .tree li a:hover+ul ul::before{
        border-color:  #94a0b4;
    }

    /*Thats all. I hope you enjoyed it.
    Thanks :)*/

</style>
<?php

function getview($data) {
    $icnon = array('user-red.png', 'user-green.png');
    $result = [];
    if ($data == 0) {
        $result['icon'] = "user-gray.png";
        $result['id'] = 0;
        $result['userId'] = 'Add New';
        $result['status'] = null;
        $result['firstName'] = "";
    } else {
        $result['icon'] = $icnon[$data[4]];
        $result['id'] = $data[0];
        $result['userId'] = $data[1];
        $result['status'] = $data[4];
        $result['firstName'] = $data[3];
    }
    return $result;
}
?>
<div class="container-fluid">
    <div class="row">

        <div class="tree">
            <ul>
                <li>
                    <?php
                    $node = getview($treedata[0]);

                    $id = "0-0-null";
                    ?>
                    <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                    <ul>
                        <!--left tree-->
                        <li>
                            <?php
                            $node = getview($treedata[1]);

                            $parentNode = getview($treedata[0]);
                            $id = "0-0-0";
                            if ($parentNode['id'] > 0)
                                $id = $parentNode['userId'] . "-0";
                            ?>
                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                            <ul>
                                <li>
                                    <?php
                                    $node = getview($treedata[3]);

                                    $parentNode = getview($treedata[1]);
                                    $id = "0-1-0";
                                    if ($parentNode['id'] > 0)
                                        $id = $parentNode['userId'] . "-0";
                                    ?>
                                    <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                    <ul>
                                        <li>
                                            <?php
                                            $node = getview($treedata[5]);

                                            $parentNode = getview($treedata[3]);
                                            $id = "0-3-0";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-0";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                        <li>
                                            <?php
                                            $node = getview($treedata[6]);

                                            $parentNode = getview($treedata[3]);
                                            $id = "0-3-1";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-1";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <?php
                                    $node = getview($treedata[4]);

                                    $parentNode = getview($treedata[1]);
                                    $id = "0-1-1";
                                    if ($parentNode['id'] > 0)
                                        $id = $parentNode['userId'] . "-1";
                                    ?>
                                    <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                    <ul>
                                        <li>
                                            <?php
                                            $node = getview($treedata[7]);
                                            $parentNode = getview($treedata[4]);
                                            $id = "0-4-0";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-0";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                        <li>
                                            <?php
                                            $node = getview($treedata[8]);
                                            $parentNode = getview($treedata[4]);
                                            $id = "0-4-1";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-1";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <!--right tree-->
                        <li>
                            <?php
                            $node = getview($treedata[2]);

                            $parentNode = getview($treedata[0]);
                            $id = "0-0-1";
                            if ($parentNode['id'] > 0)
                                $id = $parentNode['userId'] . "-1";
                            ?>
                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                            <ul>
                                <li>
                                    <?php
                                    $node = getview($treedata[9]);

                                    $parentNode = getview($treedata[2]);
                                    $id = "0-2-0";
                                    if ($parentNode['id'] > 0)
                                        $id = $parentNode['userId'] . "-0";
                                    ?>
                                    <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                    <ul>
                                        <li>
                                            <?php
                                            $node = getview($treedata[11]);

                                            $parentNode = getview($treedata[9]);
                                            $id = "0-9-0";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-0";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                        <li>
                                            <?php
                                            $node = getview($treedata[12]);

                                            $parentNode = getview($treedata[9]);
                                            $id = "0-9-1";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-1";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <?php
                                    $node = getview($treedata[10]);

                                    $parentNode = getview($treedata[2]);
                                    $id = "0-2-1";
                                    if ($parentNode['id'] > 0)
                                        $id = $parentNode['userId'] . "-1";
                                    ?>
                                    <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                    <ul>
                                        <li>
                                            <?php
                                            $node = getview($treedata[13]);

                                            $parentNode = getview($treedata[10]);
                                            $id = "0-10-0";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-0";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                        <li>
                                            <?php
                                            $node = getview($treedata[14]);

                                            $parentNode = getview($treedata[10]);
                                            $id = "0-10-1";
                                            if ($parentNode['id'] > 0)
                                                $id = $parentNode['userId'] . "-1";
                                            ?>
                                            <a href="javascript:void(0)" onclick="getnextTree(<?= $node['id']; ?>, '<?= $id; ?>')" ><img src="/images/tree/<?= $node['icon']; ?>"><br><?= $node['userId'] . "-" . $node['firstName']; ?></a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div id="frm"></div>
<script>
   //    function getnextTree(id, pid) {
//        var action = (id == 0) ? "/registration/registration/registration" : "/dashboard/dashboard/downtree";
//
//        var newForm = $('<form>', {
//            'action': action,
//            'target': '_blank',
//            'method': 'post'
//        }).append($('<input>', {
//            'name': 'id',
//            'value': id,
//            'type': 'hidden'
//        }));
//        $("#frm").append(newForm);
//
//        var parent = pid.split("-");
//        if (parent[0] == '0') {
//            console.log("no parent");
//            return false;
//        } else {
//            newForm.append($('<input>', {
//                'name': 'pid',
//                'value': parent[0],
//                'type': 'hidden'
//            }));
//            newForm.append($('<input>', {
//                'name': 'ChildNode',
//                'value': parent[1],
//                'type': 'hidden'
//            }));
//        }
//
//        newForm.submit();
//    }

function getnextTree(id, pid) {
        //var action = (id == 0) ? "/registration/registration/registration" : "/dashboard/dashboard/maintree";
        if(id == 0){
            var action = "/registration/registration/registration";
        var newForm = $('<form>', {
            'action': action,
            'target': '_blank',
            'method': 'post'
        }).append($('<input>', {
            'name': 'id',
            'value': id,
            'type': 'hidden'
        }));
        $("#frm").append(newForm);

        var parent = pid.split("-");
        if (parent[0] == '0') {
            console.log("no parent");
            return false;
        } else {
            newForm.append($('<input>', {
                'name': 'pid',
                'value': parent[0],
                'type': 'hidden'
            }));
            newForm.append($('<input>', {
                'name': 'ChildNode',
                'value': parent[1],
                'type': 'hidden'
            }));
        }

        newForm.submit();
        }else{
            var action = "/dashboard/dashboard/downtree";
        var newForm = $('<form>', {
            'action': action,
            //'target': '_blank',
            'method': 'post'
        }).append($('<input>', {
            'name': 'id',
            'value': id,
            'type': 'hidden'
        }));
        $("#frm").append(newForm);

        var parent = pid.split("-");
        if (parent[0] == '0') {
            console.log("no parent");
            return false;
        } else {
            newForm.append($('<input>', {
                'name': 'pid',
                'value': parent[0],
                'type': 'hidden'
            }));
            newForm.append($('<input>', {
                'name': 'ChildNode',
                'value': parent[1],
                'type': 'hidden'
            }));
        }

        newForm.submit();
        
        }
    }
</script>