<?php  ?>
<div class="row">
    <div class="col-lg-10">
        <section class="panel">
            <div class="panel-body">
                <div class="bordered-panel" id="print">
                    <table class="table table-full-width table-centered">
                        <tr>
                            <th colspan="8" class="tdheadmain">Growdreammaker Pvt. Ltd.</th>
                        </tr>
                        <tr>
                            <td colspan="8">office address</td>
                        </tr>
                        <tr>
                            <td colspan="8" class="">Commission Statement</td>
                        </tr>
                        <tr>
                            <td colspan="4" class="tdhead">Distributor Details</td>

                            <td colspan="4" class="tdhead">Payout Details</td>
                        </tr>
                        <tr>
                            <td>Distributor Name :</td>
                            <td colspan="3">xyz asdf adsfas asdf</td>
                            <td>Week Payout No. :</td>
                            <td colspan="3">1545</td>
                        </tr>
                        <tr>
                            <td>Distributor Id :</td>
                            <td colspan="3">adsfas fsa</td>
                            <td>Period :</td>
                            <td colspan="3">11-01-2018 To 23-01-2018</td>
                        </tr>
                        <tr>
                            <td>Address :</td>
                            <td colspan="3">adkj adsjkj jasdf jkj sadj jkjasdf </td>
                            <td></td>
                            <td colspan="3"></td>
                        </tr>   
                        <tr>
                            <td>Mobile No. :</td>
                            <td colspan="3">354464564564</td>
                            <td></td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td>City :</td>
                            <td colspan="3">Aurangabad</td>
                            <td></td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td>State :</td>
                            <td colspan="3">Maharashtra</td>
                            <td></td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td>Pin Code :</td>
                            <td colspan="3">431001</td>
                            <td></td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td colspan="8">PAYOUT DETAILS</td>
                        </tr>
                        <tr>
                            <td colspan="2">Commission(s)</td>
                            <td colspan="2">Amount(in INR)</td>
                            <td colspan="2">Deduction(s)</td>
                            <td colspan="2">Amount(In INR)</td>
                        </tr>
                        <tr>
                            <th colspan="2">Binary Commission</th>
                            <td colspan="2">125480</td>
                            <td colspan="2">ADMIN CHARGE</td>
                            <td colspan="2"> 125029 </td>
                        </tr>
                        <tr>
                            <td colspan="2">Direct Binary Commission</td>
                            <td colspan="2"> </td>
                            <td colspan="2">TDS</td>
                            <td colspan="2"> 6250 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2">Advance</td>
                            <td colspan="2"> 0.00 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2">Total</td>
                            <td colspan="2"> 18750 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2">Amount Payable (In INR)</td>
                            <td colspan="2"> 106279 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2"> Brought Forward (In INR)</td>
                            <td colspan="2"> 0.00 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2"> Total Amount Payable (In INR)</td>
                            <td colspan="2"> 106279 </td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                            <td colspan="2"> Carried Forward (In INR)</td>
                            <td colspan="2"> 0.00 </td>
                        </tr>
                        <tr>
                            <td colspan="2"> Total </td>
                            <td colspan="2"> 125029 </td>
                            <td colspan="2"> Net Payable (In INR)</td>
                            <td colspan="2"> 106279</td>
                        </tr>
                        <tr>
                            
                            <td colspan="8">*This is computer generated statement, no signature required.</td>
                        </tr>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>
<style>
    .bordered-panel{
        border: 2px solid #006;
    }
    .table-centered td{
        text-align: center;
    }
    .tdheadmain{
        font-size: 30px;
        text-align: center;
        color: #003bb3;
    }
    .tdhead{
        font-size: 20px;
        text-align: center;
        color: #003bb3;
    }
</style>
