<?php
//echo "<pre>"; print_r ($welcomeData); echo "</pre>"; die; 
?>
<div class="row">
    <div class="col-lg-10">
        <section class="panel">
            <div class="panel-body">
                <div class="welcomeForm">
                    <div class="fromInner">
                        <div class="container">
                        <div class="row">
                        <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 clearfix">
                            <div class="col-sm-3 col-xs-3">
                                <img class="img-thumbnail" src="/images/GDM-LOGO.png" alt="" height="150px" width="150px"/>
                            </div>
                            <div class="col-sm-8 col-xs-8" style="text-align: center;"><h1 class="logo">Grow Dream Maker Pvt. Ltd.</h1></div>
                        </div>
                       
                        <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 text-center clearfix" style="background: #34495e; margin: 15px 0px; padding: 5px;">
                            <div style="color:#fff; margin: 5px;"><b>Welcome Letter</b></div>
                        </div>
                        <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12">
                            <div class="col-sm-12">
                                Dear  <strong><?php echo $welcomeData[0]->firstName . " " . $welcomeData[0]->middleName . " " . $welcomeData[0]->lastName; ?>.</strong> 
                            </div>
                            <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12">
                                Welcome to the family of Grow Dream Maker Pvt. Ltd.<br>
                                You have been enrolled successfully to the Family of Grow Dream Maker Pvt. Ltd. with the following details  <br/>

                                <br>
                            </div>
                        </div>
                        <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 clearfix">
                            <div class="col-lg-6 col-sm-12 col-xs-12">
                                <div class="col-lg-6 col-xs-6"><strong>Member Id</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[0]->user_id; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Parent Id</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo ($welcomeData[0]->parent)?$welcomeData[0]->parent:"NA"; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Sponsor Id</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo ($welcomeData[0]->sponserId)?$welcomeData[0]->sponserId:"NA"; ?></div>
<!--                                <div class="col-lg-6 col-xs-6"><strong>User Group</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; ???</div>-->
                                <div class="col-lg-6 col-xs-6"><strong>Date Of Registration</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo date_format(date_create($welcomeData[0]->created_at),"d-M-Y"); ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Product with Registration</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[0]->product; ?></div> 
                                 
                            </div>
                            
                            <div class="col-lg-6 col-sm-12 col-xs-12 clearfix">
                                <div class="col-lg-6 col-xs-6"><strong>Full Name</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[0]->firstName.' '.$welcomeData[0]->lastName; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Middle Name</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[1]->fatherName; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Contact No.</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[0]->mobileNo; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>Address</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[1]->address; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>City (With Pincode)</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[1]->city.' -'.$welcomeData[1]->postalCode; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>State</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[1]->state; ?></div>
                                <div class="col-lg-6 col-xs-6"><strong>PAN No</strong></div>
                                <div class="col-lg-6 col-xs-6"> : &nbsp;&nbsp; <?php echo $welcomeData[1]->panCard; ?></div>
                            </div>
                             
 
                        </div>
                            <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12   clearfix" style="margin-top: 10px;  padding: 10px; "> 
                            <strong>Grow Dream Maker Pvt. Ltd.</strong>
 
                        </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
<style type="text/css">
    .welcomeForm{
        border: 1px solid #ccc;
    }
    .fromInner{
        padding: 10px;
    }
    div{
        margin: 3px 0;
    }
</style>