<?php
// module/Registration/view/registration/registration/registration.phtml:
$title = 'Register with us';
$this->headTitle($title);
       $signurl="/signin";

?>


<center>
                    <div style="width: 50%; font-size: 1.6em; margin-bottom: 60px;">
                                            </div>
                    <div class="middle">
                        <div id="login">
      
   <?php
   if(isset($success))
{
       
    echo "<div class='alert alert-success'>Pasword Changed.</div><a href='".$signurl."'>Login Here</a>";
}
else if(isset($iderr))
{
    echo "<div class='alert alert-warning'>Oops Something is wrong.</div>";
}
else
{
    
   
   if(isset($errCpass))
    {
        echo "<div class='alert alert-danger'>Password and Confirm Password Should Be Same.</div>";
    }
   if(isset($errOtp))
    {
        echo "<div class='alert alert-danger'>Invalid OTP.</div>";
    }
                $form = $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
        <fieldset class="clearfix">
                                    <p><span class="fa fa-key"></span>
                                        <?php	echo $this->formRow($form->get('otp')); ?>
                                 </p>
                                    <p><span class="fa fa-lock"></span>
                                        <?php	echo $this->formRow($form->get('pass')); ?>
                                 </p>
                                 <!-- JS because of IE support; better: placeholder="Username" -->
                                    <p><span class="fa fa-lock"></span><?php	echo $this->formRow($form->get('cpass')); ?></p> <!-- JS because of IE support; better: placeholder="Password" -->

                                    <div>
                                       <!-- <span class="pull-left" style="display: inline-block;"><a class="small-text" href="#">Forgot password?</a></span>-->
                                        <span class="pull-right" style="text-align:right;  display: inline-block;">
                                            <input type="reset" value="Cancel"> <?php	echo $this->formRow($form->get('submit')); ?>                                           
                                        </span>
                                    </div>

                                </fieldset>
        
                    <?php //echo $this->formPassword($form->get('pass')); ?>
                    <?php //echo $this->formElementErrors($form->get('pass')); ?>
                    <?php //echo $this->formPassword($form->get('cpass')); ?>
                    <?php //echo $this->formElementErrors($form->get('cpass')); ?>
         
 
        <?php //echo $this->formSubmit($form->get('submit')); ?>
        
        <br> 
       <div class="checkbox">
        
       Don't want to reset password ? <a href="<?php echo $signurl;?>">Sign In</a> </div>
               
      <?php echo $this->form()->closeTag($form); ?>

     <?php }
 ?>
 <div class="clearfix"></div>

                        </div> <!-- end login -->
                        <div class="logo">
                            <img class="img img-responsive" src="/images/GDM-LOGO.png" alt="LOGO" style="height: 3em;"/>
                            <div class="clearfix"></div>
                        </div>

                    </div>
                </center>