<?php
$title = 'Payment Details';
$this->headTitle($title);
?>
<div class="col-lg-12 margin-top" style="padding-top: 10px;">
<h3>Payment Released</h3>
</div>
<hr style="border-bottom: 1px solid #ccc">
    
<div class="container-fluid">

    <div class="row" style="padding: 20px;">
        <div class="col-lg-12" style="padding-bottom: 15px;">
            <table class="table table-hover " id="userList" width="100%">
                <thead>
                    <tr>
                        <th>Sr</th>
                        <th>uID</th>
                        <th>User ID</th>
                        <th>User Name</th>
                        <th>LHS Count</th>
                        <th>RHS Count</th>
                        <th>LHS BV</th>
                        <th>RHS BV</th>
                        <th>Paid Amount</th>
                        <th>Total Paid till date</th>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>


<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" />
<link rel="stylesheet" type="text/css" href="/datatable/dataTables.bootstrap.css" />

<script>
    td = $('#userList').DataTable({
        // stateSave: true,
        responsive: true,
        "language": {
            "processing": '<div class="LoadingMsg"><img src="/images/loading.gif">&nbsp; Loading....</div>',
           // "info": "of _TOTAL_ entries.",
            "lengthMenu": "Showing _MENU_",
        },
        "processing": true,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        "pageLength": 10,
        "serverSide": true,
        "ajax": {
            "url": "paymentreleasedatserver",
//                                    "data": function (post) {
//                                        post.org = orgnization;
//                                        post.category = category;
//                                        post.dept = dept;
//                                        post.branch = branch;
//
//                                    },
        },
        "fnRowCallback": function (nRow, aData, iDisplayIndex) {
//                                        console.log(aData);
            var $nRow = $(nRow); // cache the row wrapped up in jQuery
            //$("#userList_length").css('float', 'left');
            //$("#userList_info").css('float', 'left');
            //$("#userList_info").css('margin', '0 0 0 5px');
        },
//        "sDom": '<"top">rt<"bottom listingTableFooter"<"listingPageCountDiv"li><"clear"><"listingPaginationDiv"p>><"clear">',
        "columnDefs": [
            {
                "targets": [1],
                "visible": false,
                "searchable": false,
            },
            {
                "mRender": function (data, type, row) {                   
                    if (row[11] == 1) {
                        return "Paid" + ' &nbsp; <a href=javascript:; class="icon_printer" style="font-size-adjust:0.9"></a>';
                    } else {
                        return "Pending";
                    }
                },
                "targets": [-1],
            },
        ],
        "order": [[1, 'desc']],
    });

$(document).on("click",".icon_printer", function(){
alert("Invoice comming Soon")
});
</script>