<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('GDM - Signin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/paper-dashboard.css'))
                        ->prependStylesheet($this->basePath('css/animate.min.css.css'))
//                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/paper-dashboard.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <style type="text/css">
            @charset "utf-8";
            @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css);
            div.main{
                background: #0264d6; /* Old browsers */
                background: -moz-radial-gradient(center, ellipse cover,  #0264d6 1%, #1c2b5a 100%); /* FF3.6+ */
                background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(1%,#0264d6), color-stop(100%,#1c2b5a)); /* Chrome,Safari4+ */
                background: -webkit-radial-gradient(center, ellipse cover,  #0264d6 1%,#1c2b5a 100%); /* Chrome10+,Safari5.1+ */
                background: -o-radial-gradient(center, ellipse cover,  #0264d6 1%,#1c2b5a 100%); /* Opera 12+ */
                background: -ms-radial-gradient(center, ellipse cover,  #0264d6 1%,#1c2b5a 100%); /* IE10+ */
                background: radial-gradient(ellipse at center,  #0264d6 1%,#1c2b5a 100%); /* W3C */
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#0264d6', endColorstr='#1c2b5a',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
                height:calc(100vh);
                width:100%;
            }

            [class*="fontawesome-"]:before {
                font-family: 'FontAwesome', sans-serif;
            }

            /* ---------- GENERAL ---------- */

            * {
                box-sizing: border-box;
                margin:0px auto;

                &:before,
                    &:after {
                    box-sizing: border-box;
                }

            }

            body {

                color: #606468;
                font: 87.5%/1.5em 'Open Sans', sans-serif;
                margin: 0;
            }

            a {
                color: #eee;
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
                color: #000;
            }

            input {
                border: none;
                font-family: 'Open Sans', Arial, sans-serif;
                font-size: 14px;
                line-height: 1.5em;
                padding: 0;
                -webkit-appearance: none;
            }

            p {
                line-height: 1.5em;
            }

            .clearfix {
                *zoom: 1;

                &:before,
                    &:after {
                    content: ' ';
                    display: table;
                }

                &:after {
                    clear: both;
                }

            }

            .container {
                left: 50%;
                position: fixed;
                top: 50%;
                transform: translate(-50%, -50%);
            }

            /* ---------- LOGIN ---------- */

            #login form{
                width: 250px;
            }
            #login, .logo{
                display:inline-block;
                width:40%;
            }
            #login{
                border-right:1px solid #fff;
                padding: 0px 22px;
                width: 59%;
            }
            .logo{
                color:#fff;
                font-size:50px;
                line-height: 125px;
            }

            #login form span.fa {
                background-color: #fff;
                border-radius: 3px 0px 0px 3px;
                color: #000;
                display: block;
                float: left;
                height: 50px;
                font-size:24px;
                line-height: 50px;
                text-align: center;
                width: 50px;
            }

            #login form input {
                height: 50px;
            }
            fieldset{
                padding:0;
                border:0;
                margin: 0;

            }
            #login form input[type="text"], input[type="password"] {
                background-color: #fff;
                border-radius: 0px 3px 3px 0px;
                color: #000;
                margin-bottom: 1em;
                padding: 0 16px;
                width: 200px;
            }

            #login form input[type="submit"] {
                border-radius: 3px;
                -moz-border-radius: 3px;
                -webkit-border-radius: 3px;
                background-color: #1d8e01;
                color: #eee;
                font-weight: bold;
                /* margin-bottom: 2em; */
                text-transform: uppercase;
                padding: 5px 10px;
                height: 30px;
            }

            #login form input[type="submit"]:hover {
                background-color: #56e20f;
            }


            #login form input[type="reset"] {
                border-radius: 3px;
                -moz-border-radius: 3px;
                -webkit-border-radius: 3px;
                background-color: #b51a1a;
                color: #eee;
                font-weight: bold;
                /* margin-bottom: 2em; */
                text-transform: uppercase;
                padding: 5px 10px;
                height: 30px;
            }

            #login form input[type="reset"]:hover {
                background-color: #fb481f;
            }

            #login > p {
                text-align: center;
            }

            #login > p span {
                padding-left: 5px;
            }
            .middle {
                display: flex;
                width: 600px;
            }
            li{color:#fff; font-size:1.5em;}
        </style>
    </head>
    <body>
      
<div class="main">
            <div class="container">                
            <?php echo $this->content; ?>
            </div>

        </div>

    </body>
</html>
