<?php
$title = 'All Users';
$this->headTitle($title);

/* @var $userAtLeft type */
//$userAtLeft = $this->userAtLeft;
$totalPriceL = 0;
$totalBvL = 0;
$totalPriceR = 0;
$totalBvR = 0;
$lscountL = 0;
$lscountR = 0;
foreach ($userAtLeft as $key => $value) {
   // $totalPriceL += $value['price'];
    $totalBvL += $value['baseValue'];
    $totalPriceL += $value['price'];
    ++$lscountL;
}
foreach ($userAtRight as $key => $value) {
   // $totalPriceR += $value['price'];
    $totalBvR += $value['baseValue'];
    $totalPriceR += $value['price'];
    ++$lscountR;
}
?>
<div class="container-fluid"  style="padding: 20px;">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel col-lg-6 col-sm-6">
                <header class="panel-heading">
                    <h1 class="text-404" style="font-size: 3em; line-height: 1.5em;" >Left Side Members</h1>
                </header>
                <div class="panel-body">
                    <div class ="col-sm-12 text-center">
                        <button class="btn btn-primary">Total Joining : <?= $lscountL ?></button>&emsp;
                        <button class="btn btn-danger">Total BV's : <?= $totalBvL ?></button>&emsp;
                        <button class="btn btn-primary">Total Business : <?= $totalPriceL ?></button>&emsp;
                    </div>
                    <div class="col-sm-12 col-lg-12 text-center" style="padding-top: 20px;">
                        <a class="btn btn-default" href="/dashboard/user/alluser?Left_Users=all" title="Click to Display Users">
                            <b class="text-error" style="font-size: 1em; line-height: 1.5em;">
                                <span class="icon_group"></span>&emsp; Show Users At Left
                            </b>
                        </a>
                    </div>
                </div>
            </section>
        </div>
        <div class="col-lg-12">
            <section class="panel col-lg-6 col-sm-6">
                <header class="panel-heading">
                    <h1 class="text-404" style="font-size: 3em; line-height: 1.5em;" >Right Side Members</h1>
                </header>
                <div class="panel-body">
                    <div class ="col-sm-12 text-center">
                        <button class="btn btn-primary">Total Joining : <?= $lscountR ?></button>&emsp;
                        <button class="btn btn-success">Total BV's : <?= $totalBvR ?></button>&emsp;
                        <button class="btn btn-primary">Total Business : <?= $totalPriceR ?></button>&emsp;
                    </div>
                    <div class="col-sm-12 col-lg-12 text-center" style="padding-top: 20px;">
                        <a class="btn btn-default" href="/dashboard/user/alluser?Right_Users=all" title="Click to Display Users">
                            <b class="text-error" style="font-size: 1em; line-height: 1.5em;">
                                <span class="icon_group"></span>&emsp; Show Users At Right
                            </b>
                        </a>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<div class="container-fluid"  style="padding: 20px;">
    <div class="row">

        <?php
        if (isset($_GET['Left_Users'])) {
            userAtLeft($userAtLeft);
        }
        if (isset($_GET['Right_Users'])) {
            userAtRight($userAtRight);
        }

        // userAtRight();
        function userAtLeft($userAtLeft) {
            ?>
            <div class="col-lg-12 col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <table class="table table-bordered" id="alluser">
                            <legend>All Users At Left</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>User Id</th>
                                    <th>Name</th>
                                    <th>Product</th>
                                    <th>BV</th>
                                    <th>Price</th>
                                    <th>Status</th>

                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                /* userarray
                                 * 1: id
                                 * 2: user_id
                                 * 3: firstName
                                 * 3: Product
                                 * 4: status
                                 */
                                $lscount = 1;
                                //$userAtLeft = $this->userAtLeft;
                                foreach ($userAtLeft as $key => $value) {
                                    //$totalPriceL += $value['price'];
                                    // $totalBvL += $value['baseValue'];
                                    $statusL = "";
                                    echo "<tr>";
//                                    foreach ($value as $key1 => $value1) {
                                    echo "<td>" . $lscount . "</td>";
                                    echo "<td>" . $value['user_id'] . "</td>";
                                    echo "<td>" . (($value['gender'] == 0) ? "Mrs." : "Mr.") . ' ' . $value['firstName'] . ' ' . $value['lastName'] . "</td>";
//                                        echo "<td>" . $value['mobile'] . "</td>";
                                    echo "<td>" . $value['productName'] . "</td>";
                                    echo "<td>" . $value['baseValue'] . "</td>";
                                    echo "<td>" . $value['price'] . "</td>";
                                    if ($value['status'] == 1) {
                                        $statusL = "<span class='label label-success col-sm-10'>Active</span>";
                                    } elseif ($value['status'] == 0) {
                                        $statusL = "<span class='label label-danger col-sm-10'>Blocked</span>";
                                    } elseif ($value['status'] == 2) {
                                        $statusL = "<span class='label label-primary col-sm-10'>Un Paid</span>";
                                    }
                                    echo "<td>" . $statusL . "</td>";
//                                    }
                                    echo "</tr>";
                                    $lscount++;
                                }
//                                    echo "<tr>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>Total</th>"
//                                    . "<th>$totalBvL</th>"
//                                    . "<th>$totalPriceL</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "</tr>";
                                ?>
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
            <?php
        }

        function userAtRight($userAtRight) {
            ?>
            <div class="col-lg-12 col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <table class="table table-bordered" id="alluser">
                            <legend>All Users At Right</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>User Id</th>
                                    <th>Name</th>
                                    <th>Product</th>
                                    <th>BV</th>
                                    <th>Price</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                /* userarray
                                 * 1: id
                                 * 2: user_id
                                 * 3: firstName
                                 * 3: Product
                                 * 4: status
                                 */
                                $rscount = 1;
                                foreach ($userAtRight as $key => $value) {
//                                        $totalPriceR += $value['price'];
//                                        $totalBvR += $value['baseValue'];
                                    $statusR = "";
                                    echo "<tr>";
//                                    foreach ($value as $key1 => $value1) {
                                    echo "<td>" . $rscount . "</td>";
                                    echo "<td>" . $value['user_id'] . "</td>";
                                    echo "<td>" . (($value['gender'] == 0) ? "Mrs." : "Mr.") . ' ' . $value['firstName'] . ' ' . $value['lastName'] . "</td>";
//                                        echo "<td>" . $value['mobile'] . "</td>";
                                    echo "<td>" . $value['productName'] . "</td>";
                                    echo "<td>" . $value['baseValue'] . "</td>";
                                    echo "<td>" . $value['price'] . "</td>";
                                    if ($value['status'] == 1) {
                                        $statusR = "<span class='label label-success col-sm-10'>Active</span>";
                                    } elseif ($value['status'] == 0) {
                                        $statusR = "<span class='label label-danger col-sm-10'>Blocked</span>";
                                    } elseif ($value['status'] == 2) {
                                        $statusR = "<span class='label label-primary col-sm-10'>Un Paid</span>";
                                    }
                                    echo "<td>" . $statusR . "</td>";
//                                    }
                                    echo "</tr>";
                                    $rscount++;
                                }
//                                    echo "<tr>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "<th>Total</th>"
//                                    . "<th>$totalBvR</th>"
//                                    . "<th>$totalPriceR</th>"
//                                    . "<th>&nbsp;</th>"
//                                    . "</tr>";
                                ?>
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        <?php } ?>
    </div>
</div>
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
 <script src=" https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
 <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
 
 <script>
 $(document).ready(function() {
    $('#alluser').DataTable();
} );
 </script>



<script>
    $(document).find('#pageHeading').html('All User');
</script>
