<?php
$title = 'Top-Up';
$this->headTitle($title);

//print_r($topUpUser);
//die("topUpUser");
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="panel">
                <div class="col-lg-12 col-sm-12">
                    <div class="content">
                        <div class="row" style="padding: 20px;">
                            <table id="topuptable" class="table table-bordered" width="100%">
                                <legend>Admin Top-Up</legend>
                                <thead>
                                    <tr>
                                        <th>Sr</th>
                                        <th>User Id</th>
                                        <th>Name</th>
                                        <th>Parent Id</th>
                                        <th>Sponsor Id</th>
                                        <th>Position</th>
                                        <th>Product Name</th>
                                        <th>Base Value</th>
                                        <th>Top Up</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $r = 0;
                                    $position = "";
                                    for ($i = 0; $i < count($topUpUser); $i++) {
                                        echo('<tr>');
                                        echo('<td>' . ++$r . '</td>');
                                        echo('<td>' . $topUpUser[$i]['user_id'] . '</td>');
                                        echo('<td>' . $topUpUser[$i]['firstName'] . ' ' . $topUpUser[$i]['lastName'] . '</td>');
                                        echo('<td>' . $topUpUser[$i]['parent'] . '</td>');
                                        echo('<td>' . $topUpUser[$i]['sponserId'] . '</td>');
                                        if ($topUpUser[$i]['node'] == 1) {
                                            $position = "left";
                                        } elseif ($topUpUser[$i]['node'] == 0) {
                                            $position = "Right";
                                        }
                                        echo('<td>' . $position . '</td>');
                                        echo('<td>' . $topUpUser[$i]['productName'] . '</td>');
                                        echo('<td>' . $topUpUser[$i]['baseValue'] . '</td>');
                                        echo('<td><a href="javascript:;" class="addtopup" uId="' . $topUpUser[$i]['id'] . '" ><i class="fa fa-edit"></i></a></td>');
                                        echo('</tr>');
                                    }
                                    ?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Topup User</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modaluserid" ></div>
                   <div class="panel-body">
                <?php
//                $form = $this->form;
//                $form->prepare();
//                echo $this->form()->openTag($form);
                ?>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Product</label>
                            <?php echo $this->formRow($form->get('product')); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label>E-Pin</label>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('epin')); ?>
                        </div>
                    </div>
                    
                </div>
              
                <div class="text-right">
                     <button type="button" class="btn btn-default" id="submit" >Top Up Now</button>
                    <?php 
                    //echo $this->formSubmit($form->get('submit')); ?>
                </div>
                <div class="clearfix"></div>
                <?php // echo $this->form()->closeTag(); ?>
            </div>
<div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            </div>
            
        </div>

    </div>
</div>



<script src=" https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<link href="/admin/sweetalert/jquery.sweet-modal.min.css" rel="stylesheet" type="text/css"/>
<script src="/admin/sweetalert/jquery.sweet-modal.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        var td;
        td = $('#topuptable').DataTable({
            // stateSave: true,
            responsive: true,
            "processing": true,
            destroy: true,
            "columnDefs": [
                {
                    "searchable": false,
                    "orderable": false,
                    "targets": 0,
                    "defaultContent": ""
                },
                {
                    "targets": [-1],
                    "searchable": false,
                    "orderable": false,
                },
            ],
            "order": [[1, 'desc']]

        });

        $(document).on('click','.addtopup', function () {
            $('#modaluserid').empty();
            $('#product').val('');
            $('#epin').empty();
            $('#modaluserid').val($(this).attr('uId'));
             $('#myModal').modal('show');
        });
        
      
    });
       $(document).on('change',"#product",function () { 
//         alert("start");
            var val = $(this).val();
//         console.log(val);
//         alert(val);
            var uid =<?= $loginuid ?>;
//         if(val>=1){
            $.ajax({
                url: "/registration/registration/getepin",
                data: {productId: val, uid: uid},
                type: 'POST',
                success: function (data, textStatus, jqXHR) {
                    $("#epin").empty();
                    data = $.parseJSON(data);
                    for (var i = 0; i < data.length; i++)
                    {
//             alert(data[i]['pinId']);
                        var selected = "";
                        if (i == 0) {
                            selected = "selected='selected'";
                        }
                        $("#epin").append("<option value='" + data[i]['id'] + "' " + selected + " >" + data[i]['pinId'] + "</option>");
                    }
                }
            });
//         }
        });
         
       $(document).on('click',"#submit",function () { 
           var error = 0;
           if($('#epin').val()>0){              
               $('#epin').css('border',"1px solid #ccc");
           }else{
                $('#epin').css('border',"1px solid red");
               error=1;
           }
           if($('#product').val()>0 ){
            
                 $('#product').css('border',"1px solid #ccc");
           }else{
                  $('#product').css('border',"1px solid red");
               error=1;
           }
           if(error==1){
               return false;
           }
           console.log({productId: $('#product').val(), epin: $('#epin').val(), topup_uid:$("#modaluserid").val()});
            var uid =<?= $loginuid ?>;
//         if(val>=1){
            $.ajax({
                datatype:"json",
                url: "/dashboard/user/updatetopup",
                data: {productId: $('#product').val(), epin: $('#epin').val(), topup_uid:$("#modaluserid").val()},
                type: 'POST',
                success: function (data, textStatus, jqXHR) {
//                   self.location.reload();
                  $.sweetModal("Topup successfully");
                    $('#myModal').modal('toggle');
                }
            });
//         }
        });
        
        

</script>
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>