<?php
$title = 'All E-Pins';
$this->headTitle($title);
?>
 <div class="col-lg-12 col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <table class="table table-responsive table-bordered" id="epinall" width="100%">
                            <legend>All E-Pins</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>User Id</th>
                                    <th>Full Name</th>
                                    <th>Product Name</th>
                                    <th>E-Pin</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $r = 0;
                                for ($i = 0; $i < count($userdata); $i++) {
                                    echo('<tr>');
                                    echo('<td>' . ++$r . '</td>');
                                    echo('<td>' . $userdata[$i]['userId'] . '</td>');
                                    echo('<td>' . $userdata[$i]['firstName'].' '.$userdata[$i]['lastName'] . '</td>');
                                    echo('<td>' . $userdata[$i]['productName'] . ' - BV'.$userdata[$i]['baseValue']. '</td>');
                                    echo('<td>' . $userdata[$i]['pinId'] . '</td>');
                                    $statusStr="";
                                    switch($userdata[$i]['status']){
                                        case 0:
                                            $statusStr="<span class='label label-success col-sm-10'>Un-Used</span>";
                                            break;
                                        case 1:
                                             $statusStr="<span class='label label-info  col-sm-10'>Used</span>";
                                            break;
                                        case 2:
                                            $statusStr="<span class='label label-danger  col-sm-10'>Blocked</span>";
                                            break;
                                        
                                    }
                                    echo('<td>' . $statusStr . '</td>');
                                    echo('</tr>');
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </section>
                </div>
           
           
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
 <script src=" https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
 <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
 
 <script>
 $(document).ready(function() {
    $('#epinall').DataTable();
} );
 </script>
