<?php
$title = 'All Users';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="card">
                <div class="content">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="allproduct" width="100%">
                            <legend>All Products</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>Id</th>
                                    <th>Product Cat Id</th>
                                    <th>Product Name</th>
                                    <th>Description</th>
                                    <th>MRP</th>
                                    <th>Price</th>
                                    <th>Base Value</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
////                                print_r($dataProduct); die();
//                                $r = 0;
//                                for ($i = 0; $i < count($dataProduct); $i++) {
//                                    echo('<tr>');
//                                    echo('<td>' . ++$r . '</td>');
//                                    echo('<td>' . $dataProduct[$i]['productName'] . '</td>');
//                                    echo('<td>' . $dataProduct[$i]['baseValue'] . 'BV</td>');
//                                    echo('<td>' . $dataProduct[$i]['mrp'] . '</td>');
//                                    echo('<td>' . $dataProduct[$i]['price'] . '</td>');
//                                    echo('</tr>');
//                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/datatable/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
<link href="/datatable/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>

<script src="/datatable/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="/datatable/dataTables.bootstrap.min.js" type="text/javascript"></script>

<script>
            var status = "";

            td = $('#allproduct').DataTable({
                // stateSave: true,
                responsive: true,
                "language": {
                    "processing": '<div class="LoadingMsg"><img src="/images/loading.gif">&nbsp; Loading....</div>',
//                                    "info": "of _TOTAL_ entries.",
//                                    "lengthMenu": "Showing _MENU_",
                },
                "processing": true,
//                                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "lengthMenu": [[10, 25, 50], [10, 25, 50]],
                "pageLength": 10,
                "serverSide": true,
                "ajax": {
                    "url": "allproductserverside",
                    "data": function (post) {
                        post.status = status;
                    },
                },
                "fnRowCallback": function (nRow, aData, iDisplayIndex) {
//                                        console.log(aData);
                    var $nRow = $(nRow); // cache the row wrapped up in jQuery
                    //$("#userList_length").css('float', 'left');
                    //$("#userList_info").css('float', 'left');
                    //$("#userList_info").css('margin', '0 0 0 5px');
                },
                "columnDefs": [
                    {
                        "targets": [0],
                        "orderable": false,
                        "searchable": false,
                    },
                    {
                        "targets": [1],
                        "visible": false, },
                     
                    
                    {
                        "targets": [-1],
                        "searchable": false,
                        "mRender": function (data, type, alldata) {
                            
                            if (alldata[8] == 1) {
                                $statusR = "<a  class='label label-success col-sm-10 changestatus' id='"+alldata[1]+"' statusto='0' href='javascript:; '>Active</a>";
                            } else {
                                $statusR = "<a class='label label-danger col-sm-10 changestatus'  id='"+alldata[1]+"' statusto='1'  href='javascript:; '>Inactive</a>";
                            }  
                            return $statusR;
                        
                    },
                    },
                ],
                //                                "sDom": '<"top">rt<"bottom listingTableFooter"<"listingPageCountDiv"li><"clear"><"listingPaginationDiv"p>><"clear">',
                "order": [1, 'desc'],
            });

            // for buttons get data by category
            function tdcustomsearch(sval) {
                status = 'All' == sval ? '' : sval;
                td.draw();
            }
            
            $('#allproduct').on('click','.changestatus',function(){
                 var statusto = $(this).attr('statusto');
                 var statusof = $(this).attr('id');
                  
                $.ajax({
                url: "changeproductstatus",
                data: {statusto: statusto,statusof: statusof},
                type: 'POST',
                success: function (data, textStatus, jqXHR) {
                     
                    alert(data);
                    td.draw();
                }
            })
            });
            </script>