<?php
$title = 'All Users';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row" style="padding: 20px;">
                        <table class="table table-bordered">
                            <legend>All Products</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th>
                                    <th>Product Name</th>
                                    <th>BV</th>
                                    <th>MRP</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
//                                print_r($dataProduct); die();
                                $r = 0;
                                for ($i = 0; $i < count($dataProduct); $i++) {
                                    echo('<tr>');
                                    echo('<td>' . ++$r . '</td>');
                                    echo('<td>' . $dataProduct[$i]['productName'] . '</td>');
                                    echo('<td>' . $dataProduct[$i]['baseValue'] . 'BV</td>');
                                    echo('<td>' . $dataProduct[$i]['mrp'] . '</td>');
                                    echo('<td>' . $dataProduct[$i]['price'] . '</td>');
                                    echo('</tr>');
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
