<?php
$title = 'Transfer E-Pins';
$this->headTitle($title);
?>
 <div class="col-lg-12 col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <form action="" method="post" onsubmit="return validateme()">
                      
                        <table class="table table-responsive" id="epinall" width="100%">
                            
                                      <div class="row ">
                                <div class="col-lg-3">From : 
                                    <input  readonly="" id="from_user_id" name="from_user_id" class="form-control" value="<?=$user_id?>">
                                    <!--<div class="form-control"><?=$user_id?></div>-->  
                                </div> 
                                <div class="col-lg-3">To : <input id="to_user_id" name="to_user_id" class="form-control" value=""></div>
                            </div>
                            <br>
                            <legend> ALL UN-USED E-Pins</legend>
                            <thead>
                                <tr>
                                    <th>Sr</th> 
                                    <th>epiniId</th>
                                    <th>E-Pin</th>
                                    <th>Product Name</th>
                                    <th>Base Value</th> 
                                    <th><input type="checkbox" id="checkAll" value="1" class="checkAll" > &nbsp; <label for="checkAll"> &nbsp;<b> Check All</b></label> </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $r = 0;
                                for ($i = 0; $i < count($userdata); $i++) {
                                    echo("<tr>");
                                    echo('<td>' . ++$r . '</td>'); 
                                    echo('<td>' . $userdata[$i]['epinId'] . '</td>'); 
                                    echo('<td>' . $userdata[$i]['pinId'] . '</td>');
                                    echo('<td>' . $userdata[$i]['productName'].'</td>');
                                    echo('<td>' . $userdata[$i]['baseValue'] . '</td>');
                                    $statusStr="<input id='".$userdata[$i]['pinId']."' type='checkbox' name='epin[]' class='epins' value='". $userdata[$i]['epinId'] ."' >&nbsp;<label for='".$userdata[$i]['pinId']."' > &nbsp; ".$userdata[$i]['pinId']."</label>";
                                    echo('<td>' . $statusStr . '</td>');
                                    echo('</tr>');
                                }
                                ?>
                            
                            </tbody>
                             <tfoot>
                                <tr>
                                    <th></th> 
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th> 
                                    <th ><input type="submit" value="SUBMIT" name="submit" id="submit" class="btn btn-success col-lg-12" ></th>
                                </tr>
                            </tfoot>
                        </table>
                        </form>
                    </div>
                </section>
                </div>
           
           
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="//cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap.css" rel="stylesheet" type="text/css"/>
 <script src=" https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
 <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
 <script src="//cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.js" type="text/javascript"></script>
 
 
 <script>
 $(document).ready(function() {
    $('#epinall').DataTable({
        "pageLength": 10,
        responsive: true,
         "columnDefs": [
                {
                    "searchable": false,
                    "orderable": false,
                    "targets": 0, 
                },
                {
                    "searchable": false,
                    "orderable": false,                    
                    "visible": false,
                    "targets": 1,
                    "defaultContent": ""
                },
                {
                    "targets": [-1],
                    "searchable": false,
                    "orderable": false,
                },
            ],
//            "order": [[1    , 'ASC']]
    });
    $("#checkAll").click(function(){
      var chkall = $("#checkAll:checked" ).val();
        if(chkall==1){
            $(".epins").attr("checked",true);
        }else{
            $(".epins").attr("checked",false);
        } 
    });
    
    $(".epins").click(function(){        
         if( $(this).attr("checked")){
             $(this).parents('tr').addClass("trselected");
         }else{
             $(this).parents('tr').removeClass('trselected');
         }   
    });
     
});

 var msg = "<?=$msg?>";
  if(msg=="1"){
    alert("successfully updated");
    window.location.href="";
  }
  if(msg=="0"){
    alert("Cant updated please ensure that to 'user id' and pin must be selected");
    window.location.href="";
  }
    var uId = "<?=$uId?>";
    var user_id = "<?=$user_id?>";
     
    if(uId > 1){
//    $('#user_id').val(user_id).attr('readonly',true);
    $('#user_id').val(user_id);
    }    
    
    $(function() {
    $( "#to_user_id" ).autocomplete({
        source: '/dashboard/product/finduserbyuserid/'+$(this).val(),
     });
});    
//    $(function() {
//    $( "#from_user_id" ).autocomplete({
//        source: '/dashboard/product/finduserbyuserid/'+$(this).val(),
//     });
//});    

//     $( "#from_user_id" ).change(function(){
//        if( $( "#from_user_id").val() ==  $( "#to_user_id" ).val()){
//            $( "#to_user_id" ).val("").effect( "shake" );
////            alert("You can not Transfer Epins to self");            
//        }
//        
//     });
     $( "#to_user_id" ).change(function(){
        if( $( "#from_user_id").val() ==  $( "#to_user_id" ).val()){
            $( "#to_user_id" ).val("").effect( "shake" );
//            alert("You can not Transfer Epins to self");            
        }
     });
     
     function validateme(){
         
         var err=0;
         var errmsg="";
         if($("#from_user_id").val()==""){
             err =err+1;
             $("#from_user_id").css("border","1px solid red");
         }else{
             $("#from_user_id").css("border","1px solid #ccc");
         }
         if($("#to_user_id").val()==""){
            err =err+1;         
            $("#to_user_id").css("border","1px solid red");
         }else{
            $("#to_user_id").css("border","1px solid #ccc");
         }
         if($("input:checked").length<1){
            err =err+1;         
            errmsg=("please select one pin at least")
         } 
         if(err>0){
             if(errmsg!=""){
                 alert(errmsg);
             }else{
                 alert("Please select userid");
             }
             return false;
         }
         
     }
 
 </script>
 <style>
     .trselected{
         background: #efefef;
     }
      .ui-autocomplete{
     overflow: auto;
     background: #fafafa !important;
     border: 1px solid #d4d4d4 !important;
     max-height: 135px;
     margin-top: 2px !important;
     border-radius: 0 !important;
    }
 </style>
 
